Search implementation
dancier/dancer pull request #67
Opened 2024-12-10 10:04 UTC by jans510

2024-12-22 09:59 UTC, halbekanne requested changes

2024-12-22 09:59 UTC, halbekanne commented on src/main/java/net/dancier/dancer/dancers/DancerService.java
> +        Double longitudeRange = (double)range/112;
Das könnte ein Bug sein aber ich bin mir nicht sicher, die Division hier `range/122` müsste eine Integer-Division sein, die dann als Output in ein Double gewandelt wird. Aber auch wenn das nicht der Fall ist würde ich das von der Konsistenz her eher so schreiben, wie in der Zeile darunter:
```suggestion
        Double longitudeRange = range/112.0;
```

2024-12-22 09:59 UTC, halbekanne commented on src/main/java/net/dancier/dancer/dancers/DancerService.java
> +        Double longitudeRange = (double)range/112;
Es hat ja vermutlich einen Grund also nur damit ich es auch verstehe: Warum wird hier die Double-Klasse genutzt und darunter double als primitiver Datentyp?

2024-12-22 09:59 UTC, halbekanne commented on src/main/java/net/dancier/dancer/dancers/DancerService.java
> +    public List<PublicProfileDto> getDancersList(AuthenticatedUser authenticatedUser, Gender gender, int range) {
Ist nur eine Kleinigkeit, im Englischen würde man hier mMn Singular nehmen, `getDancerList`, z.B. eine Liste von Kandidaten wäre im Englischen candidate list, nicht candidates list.

2024-12-22 09:59 UTC, halbekanne commented on src/main/java/net/dancier/dancer/dancers/DancerService.java
> +        Double longitudeRange = (double)range/112;
Kannst du einen Kommentar schreiben wieso wir diese Divisoren genommen haben, damit wir das später noch wissen?

2024-12-22 09:59 UTC, halbekanne commented on src/test/java/net/dancier/dancer/dancers/DancerControllerTest.java
Ich würde noch einen Test hinzufügen, dafür was passiert, wenn man range/gender nicht angibt. Sind die Werte dann null und kann das Backend damit umgehen? Wenn wir die beiden Such-Parameter als mandatory definieren, geben wir dann einfach eine leere Liste aus?

2024-12-22 14:18 UTC, jans510 commented on src/main/java/net/dancier/dancer/dancers/DancerService.java
> +        Double longitudeRange = (double)range/112;
done

2024-12-22 14:19 UTC, jans510 commented on src/test/java/net/dancier/dancer/dancers/DancerControllerTest.java
Ich hab für Range mal einen default value angesetzt (20 km). Gender würde ich als required vorsehen und einen bad request Treturnen, falls der nicht gesetzt ist

2024-12-22 14:20 UTC, jans510 commented on src/main/java/net/dancier/dancer/dancers/DancerService.java
> +        Double longitudeRange = (double)range/112;
Hatte keinen Grund, ich habs gefixt

2024-12-24 13:35 UTC, halbekanne approved these changes

2024-12-25 08:38 UTC, merged